Task: "BSRID"

BasicSettings:
  Seed: 0
  ImageSize: 64
  ReplayBufferOnGPU: True

JointTrain:
  SampleMaxSteps: 100020
  BufferMaxLength: 100000
  BufferWarmUp: 1024
  ContextLength: 16
  NumEnvs: 1
  RID: 2
  BatchSize: 16
  BatchLength: 64
  ImagineBatchSize: 1024
  ImagineContextLength: 8
  ImagineBatchLength: 16
  TrainDynamicsEverySteps: 1
  TrainAgentEverySteps: 1
  Temperature: 20000
  SaveEverySteps: 2500
  BalancedSample: True

Models:
  WorldModel:
    InChannels: 3
    TransformerMaxLength: 64
    TransformerHiddenDim: 512
    TransformerNumLayers: 2
    TransformerNumHeads: 8

  Agent:
    NumLayers: 2
    HiddenDim: 512
    Gamma: 0.985
    Lambda: 0.95
    EntropyCoef: 3E-4
